### ISSUE TITLE
Modbus registers

### ISSUE THREAD

**Issue by geduxas** [ahinko/tcpsolis2mqtt#35]
If you interested here is modbus registers which i got.

[_Without Control Grid-Tied EN 2021.5.26_RS485_MODBUS.pdf](https://github.com/ahinko/tcpsolis2mqtt/files/14963050/_Without.Control.Grid-Tied.EN.2021.5.26_RS485_MODBUS.pdf)

Also for modbus optimisation, it's possilbe to get bigger chunks of data from modbus at once, and after that stripe it to variables. 
What to know about modbus, you are requesting address and length of data, so by doing this way at it is now you make request for each bit of value that why it take match more time and delay.

**Comment by ahinko** [comment]
Hi @geduxas

Thank you for the updated list of registers.

I should have figured it out that I could query for more registers at the same time. I even do that when querying for the current date and time. 🤦

I'm sure I can find this out by googling or testing but do know if there is a limit to how many registers we can get at the same time? I will look in to this when I have some time. 

Thank you again for the info!

**Comment by geduxas** [comment]
I think it's depends to solis logger/inverter memory buffer.. i think by test you could find it.. for while tried to get 20bits, without any problem's.
