### ISSUE TITLE
Data logger version update

### ISSUE THREAD

**Issue by MichaelEFlip** [ahinko/tcpsolis2mqtt#46]
Can you describe here and for example in the readme how to get a firmware update of the data logger?
Mine is 10010109 and is only partially working with tcpsolis2mqtt.

I have two inverters connected to the logger: S5-EH1P4.6K-L and S5-GR3P15K

Thanks!

**Comment by ahinko** [comment]
Hi @MichaelEFlip, good point, I will update the readme. 

What I did was send an email to a support address for my country that I found here: https://www.solisinverters.com/se/contactus.html and asked them to update my inverter and logger. I also included the serial number of the inverter and logger. It took less than 24 hours if I remember correctly.
